sudo: required
services:
  - docker

before_install:
  - docker build -t adityajad0610/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true adityajad0610/react-test npm run test

after_success:
  - docker build -t adityajad0610/multi-client ./client
  - docker build -t adityajad0610/multi-nginx ./nginx
  - docker build -t adityajad0610/multi-server ./server
  - docker build -t adityajad0610/multi-worker ./worker

  # Log into the Docker Cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Take those images and push to dockerHub.
  - docker push adityajad0610/multi-client
  - docker push adityajad0610/multi-nginx
  - docker push adityajad0610/multi-server
  - docker push adityajad0610/multi-worker  


deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "multi-docker"
  env: "Multi-docker-env"
  bucket_name: "elasticbeanstalk-us-east-1-816047125820"
  bucket_path: "docker-multi"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"


  # Multi-docker-env.eba-9zgtn3y2.us-east-1.elasticbeanstalk.com